<?php

namespace Labs\FacturationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepotRepository extends EntityRepository
{
}
