<?php

namespace Labs\FacturationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProformasProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProformasProductsRepository extends EntityRepository
{
    public function getAll($id)
    {
        $qb = $this->createQueryBuilder('pp');
        $qb->where($qb->expr()->eq('pp.proformas', ':id'));
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
