<?php

namespace Labs\FacturationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProformaProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProformaProductRepository extends EntityRepository
{
}
